apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: go-hermetic-example
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/brianwcook-tenant/go-hermetic-example/go-hermetic-example@sha256:63872462d37bfac66ccbfba5d66aed045b3dfb4083668a51de00f9fb728a7987
        name: my-go
        resources: {}
status: {}
